# Codecov configuration for SGFA qMAP-PD
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...90"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "examples/**/*"
  - "results/**/*"
  - "qMAP-PD_data/**/*"
  - "**/conftest.py"
  - "setup.py"
  - "debug_experiments.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  
flags:
  unittests:
    paths:
      - core/
      - models/
      - analysis/
      - experiments/
      - data/
      - visualization/
    carryforward: true
