# Pre-commit hooks for SGFA qMAP-PD
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(results/|qMAP-PD_data/)
      - id: end-of-file-fixer
        exclude: ^(results/|qMAP-PD_data/)
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key

  # Python code formatting with black
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=100']
        exclude: ^(results/|qMAP-PD_data/)

  # Import sorting with isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        exclude: ^(results/|qMAP-PD_data/)

  # Linting with flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        exclude: ^(results/|qMAP-PD_data/|tests/)

  # Type checking with mypy (optional, continue on error)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --show-error-codes]
        exclude: ^(tests/|results/|qMAP-PD_data/)
        additional_dependencies: [types-PyYAML, types-requests]
        verbose: true
        # Don't fail on mypy errors (research code flexibility)
        stages: [manual]

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml', '--skip', 'B101,B601']
        exclude: ^(tests/|results/|qMAP-PD_data/)
        additional_dependencies: ['bandit[toml]']

  # Docstring checks (optional, manual only)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--convention=numpy']
        exclude: ^(tests/|results/|qMAP-PD_data/|examples/)
        stages: [manual]

  # Check for debugging statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

# Exclude patterns for all hooks
exclude: |
  (?x)^(
    results/.*|
    qMAP-PD_data/.*|
    \.git/.*|
    \.mypy_cache/.*|
    \.pytest_cache/.*|
    __pycache__/.*|
    .*\.egg-info/.*|
    build/.*|
    dist/.*
  )$
