# Lightweight test configuration for parallel chain verification
# Based on main config.yaml but with reduced parameters for fast execution

# Data Configuration
data:
  data_dir: "./qMAP-PD_data"
  clinical_file: "data_clinical/clinical.tsv"
  volume_dir: "volume_matrices"
  imaging_as_single_view: true

# Experiment Configuration
experiments:
  base_output_dir: "./results"
  save_intermediate: false
  generate_plots: true

# Preprocessing Configuration
preprocessing:
  imputation_strategy: "median"
  feature_selection_method: "none"
  variance_threshold: 0.95

# Factor Stability Analysis Configuration - LIGHTWEIGHT TEST
factor_stability:
  K: 5                                  # Reduced from 20 for fast testing
  num_chains: 4                         # Keep 4 to test parallelization
  num_samples: 100                      # Reduced from 5000 for fast testing
  num_warmup: 50                        # Reduced from 1000 for fast testing
  chain_method: 'parallel'              # Test parallel execution

  # Factor matching parameters
  cosine_threshold: 0.8
  min_match_rate: 0.5

  # Effective factor counting
  sparsity_threshold: 0.01
  min_nonzero_pct: 0.05

  # Fixed parameters
  percW: 33
  slab_df: 4
  slab_scale: 2
  reghsZ: true
  target_accept_prob: 0.8

# Model Configuration
model:
  model_type: "sparse_gfa"
  K: 5
  num_samples: 100
  num_warmup: 50
  num_chains: 1
  sparsity_lambda: 0.05
  random_seed: 42
