# SGFA qMAP-PD Configuration
# Clean configuration compatible with validation system

# REQUIRED: Data Configuration
data:
  data_dir: "./qMAP-PD_data"
  imaging_as_single_view: true

# REQUIRED: Experiments Configuration
experiments:
  base_output_dir: "./results"
  save_intermediate: true
  generate_plots: true
  max_parallel_jobs: 1

# REQUIRED: Model Configuration
model:
  model_type: "sparse_gfa"
  K: 8
  num_samples: 2000
  num_warmup: 1000
  num_chains: 4
  sparsity_lambda: 0.05
  group_lambda: 0.1
  random_seed: 42

# OPTIONAL: Preprocessing Configuration
preprocessing:
  strategy: "standard"
  enable_advanced_preprocessing: true
  enable_spatial_processing: true
  imputation_strategy: "median"
  feature_selection_method: "variance"
  variance_threshold: 0.01

# OPTIONAL: Cross-validation Configuration
cross_validation:
  n_folds: 5
  n_repeats: 3
  stratified: true
  random_seed: 42

# OPTIONAL: Monitoring Configuration
monitoring:
  checkpoint_dir: "./results/checkpoints"
  log_level: "INFO"
  save_checkpoints: true
  checkpoint_interval: 200

# OPTIONAL: System Configuration
system:
  use_gpu: true
  memory_limit_gb: 32.0
  n_cpu_cores: 8

# Experiment-specific configurations
data_validation:
  preprocessing_strategies:
    minimal:
      enable_advanced_preprocessing: false
      imputation_strategy: "mean"
    standard:
      enable_advanced_preprocessing: true
      imputation_strategy: "median"
      feature_selection_method: "variance"
      variance_threshold: 0.01
    clinical_focused:
      enable_advanced_preprocessing: true
      imputation_strategy: "median"
      feature_selection_method: "variance"
      variance_threshold: 0.005

method_comparison:
  models:
    - name: "sparse_gfa"
      n_factors: [5, 8, 10]
      sparsity_lambda: [0.01, 0.1, 0.5]
    - name: "standard_gfa"
      n_factors: [5, 8, 10]
  cross_validation:
    n_folds: 5
    n_repeats: 2
  evaluation_metrics:
    - "reconstruction_error"
    - "factor_interpretability"

sensitivity_analysis:
  parameter_ranges:
    n_factors: [3, 5, 8, 10]
    sparsity_lambda: [0.01, 0.1, 0.5, 1.0]
  stability_tests:
    n_random_inits: 5
    convergence_threshold: 1e-5

performance_benchmarks:
  benchmark_configs:
    small_scale:
      n_subjects: 50
      n_features_per_view: [500, 300]
    medium_scale:
      n_subjects: 100
      n_features_per_view: [1000, 800]
  metrics_to_track:
    - "training_time"
    - "memory_usage"
    - "convergence_rate"

clinical_validation:
  validation_types:
    - "subtype_classification"
    - "disease_progression"
    - "biomarker_discovery"
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"

reproducibility:
  test_scenarios:
    - "identical_seeds"
    - "different_hardware"
  seed_values: [42, 123, 456]
  n_repetitions: 3