# Minimal test configuration for data validation
data:
  data_dir: "./qMAP-PD_data"

experiments:
  base_output_dir: "./test_results"

model:
  model_type: "sparse_gfa"
  K: 3
  num_samples: 100  # Small for fast testing
  num_warmup: 50
  num_chains: 1
  sparsity_lambda: 0.1