K_values:
- 5
- 10
- 15
cv_folds: 5
cv_group_variable: null
cv_strategy: stratified
cv_target_variable: null
data_dir: ./qMAP-PD_data
dataset: qmap_pd
description: Performance benchmarks on remote workstation
enable_memory_optimization: true
enable_profiling: true
experiment_name: remote_workstation_performance_benchmarks
num_chains: 4
num_runs_per_config: 3
num_samples: 2000
num_sources: 3
num_warmup: 1000
output_formats:
- json
- csv
percW_values:
- 25.0
- 33.0
- 50.0
performance_config: {}
preprocessing_config: {}
random_seeds:
- 42
- 123
- 456
save_diagnostics: true
save_intermediate_results: true
save_samples: false
version: '1.0'
